server:
  port:8080

netty:
  host: 127.0.0.1
  port: 7397

spring:
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    # jedis配置
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: 1000
    # lettuce配置
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000